name: Bondarevs Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
  install-pip-deps:
    runs-on: self-hosted
    steps:
      - name: Display message
        run: echo "Installing all required dependencies.."
      - name: Checkout greetings repository
        uses: actions/checkout@v3.5.2
        with:
          repository: mtararujs/python-greetings
          path: python-greetings
          ref: '4e911440a9886c7c26ccbb4eb55f0bc2a5067b51'
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install PM2
        run: npm install pm2 -g
      - name: Install dependencies
        run: pip install -r C:\Users\Gleb\AppData\Local\Programs\Python\Python312\requirements.txt
          
  deploy-to-dev:
    needs: install-pip-deps
    runs-on: self-hosted
    steps:
      - name: Display message
        run: echo "Deploying to Development environment.."
      - name: Checkout greetings repository
        uses: actions/checkout@v3.5.2
        with:
          repository: mtararujs/python-greetings
          path: python-greetings
          ref: '4e911440a9886c7c26ccbb4eb55f0bc2a5067b51'
          fetch-depth: 0
      - name: Install dependencies
        run: pip install -r C:\Users\Gleb\AppData\Local\Programs\Python\Python312\requirements.txt
      - name: Deploy to Development Environment
        run: |
          pm2 delete greetings-app-dev
          pm2 set"errorlevel=0" 
          pm2 start app.py --name greetings-app-div ----port 7001
        
  tests-on-dev:
    needs: deploy-to-dev
    runs-on: self-hosted
    steps:
      - name: Display message
        run: echo "Running tests on Development environment.."
        
  deploy-to-staging:
    needs: tests-on-dev
    runs-on: self-hosted
    steps:
      - name: Display message
        run: echo "Deploying to Staging environment.."
        
  tests-on-staging:
    needs: deploy-to-staging
    runs-on: self-hosted
    steps:
      - name: Display message
        run: echo "Running tests on Staging environment.."
        
  deploy-to-preprod:
    needs: tests-on-staging
    runs-on: self-hosted
    steps:
      - name: Display message
        run: echo "Deploying to Pre-Production environment.."
        
  tests-on-preprod:
    needs: deploy-to-preprod
    runs-on: self-hosted
    steps:
      - name: Display message
        run: echo "Running tests on Pre-Production environment.."
        
  deploy-to-prod:
    needs: tests-on-preprod
    runs-on: self-hosted
    steps:
      - name: Display message
        run: echo "Deploying to Production environment.."
        
  tests-on-prod:
    needs: deploy-to-prod
    runs-on: self-hosted
    steps:
      - name: Display message
        run: echo "Running tests on Production environment.."
