name: Bondarevs Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
  install-pip-deps:
    runs-on: self-hosted
  deploy-to-dev:
    needs: install-pip-deps
    runs-on: self-hosted
  tests-on-dev:
    needs: deploy-to-dev
    runs-on: self-hosted
  deploy-to-staging:
    needs: tests-on-dev
    runs-on: self-hosted
  tests-on-staging:
    needs: deploy-to-staging
    runs-on: self-hosted
  deploy-to-preprod:
    needs: tests-on-staging
    runs-on: self-hosted
  tests-on-preprod:
    needs: deploy-to-preprod
    runs-on: self-hosted
  deploy-to-prod:
    needs: tests-on-preprod
    runs-on: self-hosted
  tests-on-prod:
    needs: deploy-to-prod
    runs-on: self-hosted
