name: Python Application Delivery Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
  install-pip-deps:
    runs-on: self-hosted
    steps:
    - name: Checkout python-greetings repository
      uses: actions/checkout@v3.5.2
      with:
        repository: mtararujs/python-greetings
        path: python-greetings
        ref: '4e911440a9886c7c26ccbb4eb55f0bc2a5067b51'
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Install PM2
      run: npm install pm2 -g
