name: Bondarevs Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
  install-pip-deps:
    runs-on: self-hosted
    steps:
      - name: Display message
        run: echo "Installing all required dependencies.."
      - name: Checkout greetings repository
        uses: actions/checkout@v3.5.2
        with:
          repository: mtararujs/python-greetings
          path: python-greetings
          ref: 'eb3e859152a2da55751c022eb010c12c141c9845'
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install PM2
        run: npm install pm2 -g
      - name: Install dependencies
        run: pip install -r C:\Users\Gleb\AppData\Local\Programs\Python\Python312\requirements.txt
          
  deploy-to-dev:
    needs: install-pip-deps
    runs-on: self-hosted
    steps:
      - name: Display message
        run: echo "Deploying to Development environment.."
      - name: Checkout greetings repository
        uses: actions/checkout@v3.5.2
        with:
          repository: mtararujs/python-greetings
          path: python-greetings
          ref: '5702da3ed2585370912d657f3845ad1a444665ad'
          fetch-depth: 0
      - name: Install dependencies
        run: pip install -r C:\Users\Gleb\AppData\Local\Programs\Python\Python312\requirements.txt
      - name: Deploy to Development Environment
        run: |
          pm2 delete greetings-app-dev; pm2 set env:errorlevel 0
          pm2 start app.py --name greetings-app-dev --cwd ./python-greetings -- -- 7001
      - name: Check server status
        run: |
          pm2 status
        working-directory: ./python-greetings

        
  tests-on-dev:
    needs: deploy-to-dev
    runs-on: self-hosted
    steps:
      - name: Display message
        run: echo "Running tests on Development environment.."
      - name: Checkout course-js-api-framework repository
        uses: actions/checkout@v3.5.2
        with:
          repository: mtararujs/course-js-api-framework
          path: course-js-api-framework
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup tests
        run: |
          npm --cwd ./course-js-api-framework cache clean --force
          npm --cwd ./course-js-api-framework install mocha --no-save
          npm --cwd ./course-js-api-framework install
      - name: Run tests
        run: |
          npm --cwd ./course-js-api-framework run greetings greetings_dev
        
  deploy-to-staging:
    needs: tests-on-dev
    runs-on: self-hosted
    steps:
      - name: Display message
        run: echo "Deploying to Staging environment.."
      - name: Checkout python-greetings repository
        uses: actions/checkout@v3.5.2
        with:
          repository: mtararujs/python-greetings
          path: python-greetings
          ref: '4e911440a9886c7c26ccbb4eb55f0bc2a5067b51'
          token: ${{ secrets.GITHUB_TOKEN }}
        
  tests-on-staging:
    needs: deploy-to-staging
    runs-on: self-hosted
    steps:
      - name: Display message
        run: echo "Running tests on Staging environment.."
      - name: Checkout course-js-api-framework repository
        uses: actions/checkout@v3.5.2
        with:
          repository: mtararujs/course-js-api-framework
          path: course-js-api-framework
          token: ${{ secrets.GITHUB_TOKEN }}
        
  deploy-to-preprod:
    needs: tests-on-staging
    runs-on: self-hosted
    steps:
      - name: Display message
        run: echo "Deploying to Pre-Production environment.."
      - name: Checkout python-greetings repository
        uses: actions/checkout@v3.5.2
        with:
          repository: mtararujs/python-greetings
          path: python-greetings
          ref: '4e911440a9886c7c26ccbb4eb55f0bc2a5067b51'
          token: ${{ secrets.GITHUB_TOKEN }}
        
  tests-on-preprod:
    needs: deploy-to-preprod
    runs-on: self-hosted
    steps:
      - name: Display message
        run: echo "Running tests on Pre-Production environment.."
      - name: Checkout course-js-api-framework repository
        uses: actions/checkout@v3.5.2
        with:
          repository: mtararujs/course-js-api-framework
          path: course-js-api-framework
          token: ${{ secrets.GITHUB_TOKEN }}
        
  deploy-to-prod:
    needs: tests-on-preprod
    runs-on: self-hosted
    steps:
      - name: Display message
        run: echo "Deploying to Production environment.."
      - name: Checkout python-greetings repository
        uses: actions/checkout@v3.5.2
        with:
          repository: mtararujs/python-greetings
          path: python-greetings
          ref: '4e911440a9886c7c26ccbb4eb55f0bc2a5067b51'
          token: ${{ secrets.GITHUB_TOKEN }}
        
  tests-on-prod:
    needs: deploy-to-prod
    runs-on: self-hosted
    steps:
      - name: Display message
        run: echo "Running tests on Production environment.."
      - name: Checkout course-js-api-framework repository
        uses: actions/checkout@v3.5.2
        with:
          repository: mtararujs/course-js-api-framework
          path: course-js-api-framework
          token: ${{ secrets.GITHUB_TOKEN }}
